export const GET_CART_ITEMS_REQUEST = "GET_CART_ITMES_REQUEST";
export const GET_CART_ITEMS_SUCCESS = "GET_CART_ITMES_SUCCESS";
export const GET_CART_ITEMS_FAILURE = "GET_CART_ITMES_FAILURE";

export const UPDATE_CART_ITEMS_REQUEST = "UPDATE_CART_ITMES_REQUEST";
export const UPDATE_CART_ITEMS_SUCCESS = "UPDATE_CART_ITMES_SUCCESS";
export const UPDATE_CART_ITEMS_FAILURE = "UPDATE_CART_ITMES_FAILURE";

export const DELETE_CART_ITEMS_REQUEST = "DELETE_CART_ITMES_REQUEST";
export const DELETE_CART_ITEMS_SUCCESS = "DELETE_CART_ITMES_SUCCESS";
export const DELETE_CART_ITEMS_FAILURE = "DELETE_CART_ITMES_FAILURE";
